//
// This file was auto-generated by a tool.  Do not modify.
//
using System.Resources;
using System.Runtime.InteropServices;

[assembly: NeutralResourcesLanguageAttribute("")]
[assembly: ComVisibleAttribute(false)]
